config/routes.rb
Rails.application.routes.draw do
  get 'projects/dashboard'
  get 'projects/create'
  post 'projects/create'

  root 'projects#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, :description, :state, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :dashboard
  
  def dashboard
    @project = Project.new
    if params[:state].present?
      @projects = Project.where('state = ?', params[:state])
    else
      @projects = Project.all
    end
  end

  def create
    @project = Project.create(name: params[:name], description: params[:description], starting_date: params[:starting_date], do_date: params[:do_date], state: params[:state])
    @projects = Project.all 
    render :dashboard
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>

  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/dashboard.html.erb
<h1 class="text-center text-decoration-underline">Panel de proyectos</h1>

<h1 class="text-center text-decoration-underline mt-2">Gestor de Proyectos</h1>

<form action="<%= projects_dashboard_path%>">
        <select name="state" class="form-select">
            <option value="">Todos</option>
            <option value="propuesta">Propuesta</option>
            <option value="progreso">Progreso</option>
            <option value="terminado">Terminado</option>
        </select>
        <input class="btn btn-dark text-light my-4 translate-midle" type="submit" value="Buscar">
</form>

<div class="table-responsive">
    <table class="table">
            <tr>
                <th> Nombre </th>
                <th> Descripción </th>
                <th> Fecha de inicio </th>
                <th> Fecha de término </th>
                <th> Estado </th>
            </tr>

        <% @projects.each do |project|%>
            <tr>
                <td><%= project.name %></td>
                <td><%= project.description %></td>
                <td><%= project.starting_date%></td>
                <td><%= project.do_date%></td>
                <td><%= project.state %></td>
            </tr>
        <%end%>
    </table>
</div>


<h2 class="text-center text-decoration-underline mt-5">Crear proyecto nuevo </h2>
<form id="create_proyect" method="get" action="<%= projects_create_path%>">

    <div class="mb-3">
        <label for="form_name" class="form-label">Nombre</label>
        <input name="name" class="form-control">
    </div>

    <div class="mb-3">
        <label for="form_descripcion" class="form-label">Descripción</label>
        <input name="description" class="form-control" type="textarea">
    </div>

        <div class="mb-3">
            <label for="form_starting_date" class="form-label" type="date" >Fecha de Inicio</label>
            <input name="starting_date" class="datepicker" data-date-format="dd/mm/yyyy" placeholder="dd/mm/yyyy" >
        </div>

        <div class="mb-3">
            <label for="form_do_date" class="form-label" type="date" >Fecha de Término</label>
            <input name="do_date" class="datepicker" data-date-format="dd/mm/yyyy" placeholder="dd/mm/yyyy" >
        </div>

    <div class="mb-3">
        <label for="form_state" class="form-label">Estado</label>
        <select name="state" class="form-select">
            <option selected>Seleccione una de las opciones</option>
            <option value="propuesta">Propuesta</option>
            <option value="progreso">Progreso</option>
            <option value="terminado">Terminado</option>
        </select>
    </div>
    
        <input class="btn btn-dark text-light" type="submit" value="Enviar">
    
</form>
<div class="container mt-2">
    <% if @project.errors.any?%>
        <div id="error_explanation">
            <h4>Su proyecto no pudo salvarse, por favor, vuelva a intentarlo </h4>
        
            <h5>
                <%= pluralize(@project.errors.count, "error")%>
                <p>prohibited this project from being saved: </p>
            </h5>
        
            <ul>
                <% @project.errors.full_messages.each do |msg|%>
                <li> <%=msg%> </li>
                <%end%>
            </ul>
        </div>
        
    <%else%>
        <h4>Su proyecto fue ingresado con éxito</h4>
    <%end%>
</div>